//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.11 at 07:10:46 PM GMT 
//


package org.apache.storm.starter.xml;


import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.gov.tfl.tims._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.gov.tfl.tims._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Root.Disruptions }
     * 
     */
    public Root.Disruptions createRootDisruptions() {
        return new Root.Disruptions();
    }

    /**
     * Create an instance of {@link Root.Disruptions.Disruption }
     * 
     */
    public Root.Disruptions.Disruption createRootDisruptionsDisruption() {
        return new Root.Disruptions.Disruption();
    }

    /**
     * Create an instance of {@link Root.Disruptions.Disruption.RecurringSchedule }
     * 
     */
    public Root.Disruptions.Disruption.RecurringSchedule createRootDisruptionsDisruptionRecurringSchedule() {
        return new Root.Disruptions.Disruption.RecurringSchedule();
    }

    /**
     * Create an instance of {@link Root.Disruptions.Disruption.CauseArea }
     * 
     */
    public Root.Disruptions.Disruption.CauseArea createRootDisruptionsDisruptionCauseArea() {
        return new Root.Disruptions.Disruption.CauseArea();
    }

    /**
     * Create an instance of {@link Root.Disruptions.Disruption.CauseArea.Streets }
     * 
     */
    public Root.Disruptions.Disruption.CauseArea.Streets createRootDisruptionsDisruptionCauseAreaStreets() {
        return new Root.Disruptions.Disruption.CauseArea.Streets();
    }

    /**
     * Create an instance of {@link Root.Disruptions.Disruption.CauseArea.Streets.Street }
     * 
     */
    public Root.Disruptions.Disruption.CauseArea.Streets.Street createRootDisruptionsDisruptionCauseAreaStreetsStreet() {
        return new Root.Disruptions.Disruption.CauseArea.Streets.Street();
    }

    /**
     * Create an instance of {@link Root.Disruptions.Disruption.CauseArea.Streets.Street.Link }
     * 
     */
    public Root.Disruptions.Disruption.CauseArea.Streets.Street.Link createRootDisruptionsDisruptionCauseAreaStreetsStreetLink() {
        return new Root.Disruptions.Disruption.CauseArea.Streets.Street.Link();
    }

    /**
     * Create an instance of {@link Root.Disruptions.Disruption.CauseArea.Boundary }
     * 
     */
    public Root.Disruptions.Disruption.CauseArea.Boundary createRootDisruptionsDisruptionCauseAreaBoundary() {
        return new Root.Disruptions.Disruption.CauseArea.Boundary();
    }

    /**
     * Create an instance of {@link Root.Disruptions.Disruption.CauseArea.DisplayPoint }
     * 
     */
    public Root.Disruptions.Disruption.CauseArea.DisplayPoint createRootDisruptionsDisruptionCauseAreaDisplayPoint() {
        return new Root.Disruptions.Disruption.CauseArea.DisplayPoint();
    }

    /**
     * Create an instance of {@link Root.Header }
     * 
     */
    public Root.Header createRootHeader() {
        return new Root.Header();
    }

    /**
     * Create an instance of {@link Root.Disruptions.Disruption.RecurringSchedule.Schedule }
     * 
     */
    public Root.Disruptions.Disruption.RecurringSchedule.Schedule createRootDisruptionsDisruptionRecurringScheduleSchedule() {
        return new Root.Disruptions.Disruption.RecurringSchedule.Schedule();
    }

    /**
     * Create an instance of {@link Root.Disruptions.Disruption.CauseArea.Streets.Street.Link.Line }
     * 
     */
    public Root.Disruptions.Disruption.CauseArea.Streets.Street.Link.Line createRootDisruptionsDisruptionCauseAreaStreetsStreetLinkLine() {
        return new Root.Disruptions.Disruption.CauseArea.Streets.Street.Link.Line();
    }

    /**
     * Create an instance of {@link Root.Disruptions.Disruption.CauseArea.Boundary.Polygon }
     * 
     */
    public Root.Disruptions.Disruption.CauseArea.Boundary.Polygon createRootDisruptionsDisruptionCauseAreaBoundaryPolygon() {
        return new Root.Disruptions.Disruption.CauseArea.Boundary.Polygon();
    }

    /**
     * Create an instance of {@link Root.Disruptions.Disruption.CauseArea.DisplayPoint.Point }
     * 
     */
    public Root.Disruptions.Disruption.CauseArea.DisplayPoint.Point createRootDisruptionsDisruptionCauseAreaDisplayPointPoint() {
        return new Root.Disruptions.Disruption.CauseArea.DisplayPoint.Point();
    }

    /**
     * Create an instance of {@link Root.Header.PublishDateTime }
     * 
     */
    public Root.Header.PublishDateTime createRootHeaderPublishDateTime() {
        return new Root.Header.PublishDateTime();
    }

    /**
     * Create an instance of {@link Root.Header.Attribution }
     * 
     */
    public Root.Header.Attribution createRootHeaderAttribution() {
        return new Root.Header.Attribution();
    }

}
