//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.18 at 02:17:15 PM GMT 
//

package org.apache.storm.starter.timetable.xml;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.org.transxchange package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.org.transxchange
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TransXChange }
     * 
     */
    public TransXChange createTransXChange() {
        return new TransXChange();
    }

    /**
     * Create an instance of {@link TransXChange.VehicleJourneys }
     * 
     */
    public TransXChange.VehicleJourneys createTransXChangeVehicleJourneys() {
        return new TransXChange.VehicleJourneys();
    }

    /**
     * Create an instance of {@link TransXChange.VehicleJourneys.VehicleJourney }
     * 
     */
    public TransXChange.VehicleJourneys.VehicleJourney createTransXChangeVehicleJourneysVehicleJourney() {
        return new TransXChange.VehicleJourneys.VehicleJourney();
    }

    /**
     * Create an instance of {@link TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile }
     * 
     */
    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile createTransXChangeVehicleJourneysVehicleJourneyOperatingProfile() {
        return new TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile();
    }

    /**
     * Create an instance of {@link TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation }
     * 
     */
    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation createTransXChangeVehicleJourneysVehicleJourneyOperatingProfileBankHolidayOperation() {
        return new TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation();
    }

    /**
     * Create an instance of {@link TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation }
     * 
     */
    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation createTransXChangeVehicleJourneysVehicleJourneyOperatingProfileSpecialDaysOperation() {
        return new TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation();
    }

    /**
     * Create an instance of {@link TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfOperation }
     * 
     */
    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfOperation createTransXChangeVehicleJourneysVehicleJourneyOperatingProfileSpecialDaysOperationDaysOfOperation() {
        return new TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfOperation();
    }

    /**
     * Create an instance of {@link TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation }
     * 
     */
    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation createTransXChangeVehicleJourneysVehicleJourneyOperatingProfileSpecialDaysOperationDaysOfNonOperation() {
        return new TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation();
    }

    /**
     * Create an instance of {@link TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.RegularDayType }
     * 
     */
    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.RegularDayType createTransXChangeVehicleJourneysVehicleJourneyOperatingProfileRegularDayType() {
        return new TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.RegularDayType();
    }

    /**
     * Create an instance of {@link TransXChange.VehicleJourneys.VehicleJourney.Operational }
     * 
     */
    public TransXChange.VehicleJourneys.VehicleJourney.Operational createTransXChangeVehicleJourneysVehicleJourneyOperational() {
        return new TransXChange.VehicleJourneys.VehicleJourney.Operational();
    }

    /**
     * Create an instance of {@link TransXChange.Services }
     * 
     */
    public TransXChange.Services createTransXChangeServices() {
        return new TransXChange.Services();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service }
     * 
     */
    public TransXChange.Services.Service createTransXChangeServicesService() {
        return new TransXChange.Services.Service();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.StandardService }
     * 
     */
    public TransXChange.Services.Service.StandardService createTransXChangeServicesServiceStandardService() {
        return new TransXChange.Services.Service.StandardService();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.StandardService.JourneyPattern }
     * 
     */
    public TransXChange.Services.Service.StandardService.JourneyPattern createTransXChangeServicesServiceStandardServiceJourneyPattern() {
        return new TransXChange.Services.Service.StandardService.JourneyPattern();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.StandardService.JourneyPattern.Operational }
     * 
     */
    public TransXChange.Services.Service.StandardService.JourneyPattern.Operational createTransXChangeServicesServiceStandardServiceJourneyPatternOperational() {
        return new TransXChange.Services.Service.StandardService.JourneyPattern.Operational();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.OperatingProfile }
     * 
     */
    public TransXChange.Services.Service.OperatingProfile createTransXChangeServicesServiceOperatingProfile() {
        return new TransXChange.Services.Service.OperatingProfile();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.OperatingProfile.BankHolidayOperation }
     * 
     */
    public TransXChange.Services.Service.OperatingProfile.BankHolidayOperation createTransXChangeServicesServiceOperatingProfileBankHolidayOperation() {
        return new TransXChange.Services.Service.OperatingProfile.BankHolidayOperation();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation }
     * 
     */
    public TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation createTransXChangeServicesServiceOperatingProfileSpecialDaysOperation() {
        return new TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation }
     * 
     */
    public TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation createTransXChangeServicesServiceOperatingProfileSpecialDaysOperationDaysOfNonOperation() {
        return new TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.OperatingProfile.RegularDayType }
     * 
     */
    public TransXChange.Services.Service.OperatingProfile.RegularDayType createTransXChangeServicesServiceOperatingProfileRegularDayType() {
        return new TransXChange.Services.Service.OperatingProfile.RegularDayType();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.Lines }
     * 
     */
    public TransXChange.Services.Service.Lines createTransXChangeServicesServiceLines() {
        return new TransXChange.Services.Service.Lines();
    }

    /**
     * Create an instance of {@link TransXChange.Operators }
     * 
     */
    public TransXChange.Operators createTransXChangeOperators() {
        return new TransXChange.Operators();
    }

    /**
     * Create an instance of {@link TransXChange.JourneyPatternSections }
     * 
     */
    public TransXChange.JourneyPatternSections createTransXChangeJourneyPatternSections() {
        return new TransXChange.JourneyPatternSections();
    }

    /**
     * Create an instance of {@link TransXChange.JourneyPatternSections.JourneyPatternSection }
     * 
     */
    public TransXChange.JourneyPatternSections.JourneyPatternSection createTransXChangeJourneyPatternSectionsJourneyPatternSection() {
        return new TransXChange.JourneyPatternSections.JourneyPatternSection();
    }

    /**
     * Create an instance of {@link TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink }
     * 
     */
    public TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink createTransXChangeJourneyPatternSectionsJourneyPatternSectionJourneyPatternTimingLink() {
        return new TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink();
    }

    /**
     * Create an instance of {@link TransXChange.Routes }
     * 
     */
    public TransXChange.Routes createTransXChangeRoutes() {
        return new TransXChange.Routes();
    }

    /**
     * Create an instance of {@link TransXChange.RouteSections }
     * 
     */
    public TransXChange.RouteSections createTransXChangeRouteSections() {
        return new TransXChange.RouteSections();
    }

    /**
     * Create an instance of {@link TransXChange.RouteSections.RouteSection }
     * 
     */
    public TransXChange.RouteSections.RouteSection createTransXChangeRouteSectionsRouteSection() {
        return new TransXChange.RouteSections.RouteSection();
    }

    /**
     * Create an instance of {@link TransXChange.RouteSections.RouteSection.RouteLink }
     * 
     */
    public TransXChange.RouteSections.RouteSection.RouteLink createTransXChangeRouteSectionsRouteSectionRouteLink() {
        return new TransXChange.RouteSections.RouteSection.RouteLink();
    }

    /**
     * Create an instance of {@link TransXChange.StopPoints }
     * 
     */
    public TransXChange.StopPoints createTransXChangeStopPoints() {
        return new TransXChange.StopPoints();
    }

    /**
     * Create an instance of {@link TransXChange.StopPoints.StopPoint }
     * 
     */
    public TransXChange.StopPoints.StopPoint createTransXChangeStopPointsStopPoint() {
        return new TransXChange.StopPoints.StopPoint();
    }

    /**
     * Create an instance of {@link TransXChange.StopPoints.StopPoint.StopClassification }
     * 
     */
    public TransXChange.StopPoints.StopPoint.StopClassification createTransXChangeStopPointsStopPointStopClassification() {
        return new TransXChange.StopPoints.StopPoint.StopClassification();
    }

    /**
     * Create an instance of {@link TransXChange.StopPoints.StopPoint.StopClassification.OffStreet }
     * 
     */
    public TransXChange.StopPoints.StopPoint.StopClassification.OffStreet createTransXChangeStopPointsStopPointStopClassificationOffStreet() {
        return new TransXChange.StopPoints.StopPoint.StopClassification.OffStreet();
    }

    /**
     * Create an instance of {@link TransXChange.StopPoints.StopPoint.StopClassification.OffStreet.BusAndCoach }
     * 
     */
    public TransXChange.StopPoints.StopPoint.StopClassification.OffStreet.BusAndCoach createTransXChangeStopPointsStopPointStopClassificationOffStreetBusAndCoach() {
        return new TransXChange.StopPoints.StopPoint.StopClassification.OffStreet.BusAndCoach();
    }

    /**
     * Create an instance of {@link TransXChange.StopPoints.StopPoint.Place }
     * 
     */
    public TransXChange.StopPoints.StopPoint.Place createTransXChangeStopPointsStopPointPlace() {
        return new TransXChange.StopPoints.StopPoint.Place();
    }

    /**
     * Create an instance of {@link TransXChange.NptgLocalities }
     * 
     */
    public TransXChange.NptgLocalities createTransXChangeNptgLocalities() {
        return new TransXChange.NptgLocalities();
    }

    /**
     * Create an instance of {@link TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation.DaysOfOperation }
     * 
     */
    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation.DaysOfOperation createTransXChangeVehicleJourneysVehicleJourneyOperatingProfileBankHolidayOperationDaysOfOperation() {
        return new TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation.DaysOfOperation();
    }

    /**
     * Create an instance of {@link TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation.DaysOfNonOperation }
     * 
     */
    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation.DaysOfNonOperation createTransXChangeVehicleJourneysVehicleJourneyOperatingProfileBankHolidayOperationDaysOfNonOperation() {
        return new TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation.DaysOfNonOperation();
    }

    /**
     * Create an instance of {@link TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfOperation.DateRange }
     * 
     */
    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfOperation.DateRange createTransXChangeVehicleJourneysVehicleJourneyOperatingProfileSpecialDaysOperationDaysOfOperationDateRange() {
        return new TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfOperation.DateRange();
    }

    /**
     * Create an instance of {@link TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation.DateRange }
     * 
     */
    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation.DateRange createTransXChangeVehicleJourneysVehicleJourneyOperatingProfileSpecialDaysOperationDaysOfNonOperationDateRange() {
        return new TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation.DateRange();
    }

    /**
     * Create an instance of {@link TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.RegularDayType.DaysOfWeek }
     * 
     */
    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.RegularDayType.DaysOfWeek createTransXChangeVehicleJourneysVehicleJourneyOperatingProfileRegularDayTypeDaysOfWeek() {
        return new TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.RegularDayType.DaysOfWeek();
    }

    /**
     * Create an instance of {@link TransXChange.VehicleJourneys.VehicleJourney.Operational.VehicleType }
     * 
     */
    public TransXChange.VehicleJourneys.VehicleJourney.Operational.VehicleType createTransXChangeVehicleJourneysVehicleJourneyOperationalVehicleType() {
        return new TransXChange.VehicleJourneys.VehicleJourney.Operational.VehicleType();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.OperatingPeriod }
     * 
     */
    public TransXChange.Services.Service.OperatingPeriod createTransXChangeServicesServiceOperatingPeriod() {
        return new TransXChange.Services.Service.OperatingPeriod();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.StopRequirements }
     * 
     */
    public TransXChange.Services.Service.StopRequirements createTransXChangeServicesServiceStopRequirements() {
        return new TransXChange.Services.Service.StopRequirements();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.StandardService.JourneyPattern.Operational.VehicleType }
     * 
     */
    public TransXChange.Services.Service.StandardService.JourneyPattern.Operational.VehicleType createTransXChangeServicesServiceStandardServiceJourneyPatternOperationalVehicleType() {
        return new TransXChange.Services.Service.StandardService.JourneyPattern.Operational.VehicleType();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.OperatingProfile.BankHolidayOperation.DaysOfOperation }
     * 
     */
    public TransXChange.Services.Service.OperatingProfile.BankHolidayOperation.DaysOfOperation createTransXChangeServicesServiceOperatingProfileBankHolidayOperationDaysOfOperation() {
        return new TransXChange.Services.Service.OperatingProfile.BankHolidayOperation.DaysOfOperation();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation.DateRange }
     * 
     */
    public TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation.DateRange createTransXChangeServicesServiceOperatingProfileSpecialDaysOperationDaysOfNonOperationDateRange() {
        return new TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation.DateRange();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.OperatingProfile.RegularDayType.DaysOfWeek }
     * 
     */
    public TransXChange.Services.Service.OperatingProfile.RegularDayType.DaysOfWeek createTransXChangeServicesServiceOperatingProfileRegularDayTypeDaysOfWeek() {
        return new TransXChange.Services.Service.OperatingProfile.RegularDayType.DaysOfWeek();
    }

    /**
     * Create an instance of {@link TransXChange.Services.Service.Lines.Line }
     * 
     */
    public TransXChange.Services.Service.Lines.Line createTransXChangeServicesServiceLinesLine() {
        return new TransXChange.Services.Service.Lines.Line();
    }

    /**
     * Create an instance of {@link TransXChange.Operators.Operator }
     * 
     */
    public TransXChange.Operators.Operator createTransXChangeOperatorsOperator() {
        return new TransXChange.Operators.Operator();
    }

    /**
     * Create an instance of {@link TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink.From }
     * 
     */
    public TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink.From createTransXChangeJourneyPatternSectionsJourneyPatternSectionJourneyPatternTimingLinkFrom() {
        return new TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink.From();
    }

    /**
     * Create an instance of {@link TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink.To }
     * 
     */
    public TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink.To createTransXChangeJourneyPatternSectionsJourneyPatternSectionJourneyPatternTimingLinkTo() {
        return new TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink.To();
    }

    /**
     * Create an instance of {@link TransXChange.Routes.Route }
     * 
     */
    public TransXChange.Routes.Route createTransXChangeRoutesRoute() {
        return new TransXChange.Routes.Route();
    }

    /**
     * Create an instance of {@link TransXChange.RouteSections.RouteSection.RouteLink.From }
     * 
     */
    public TransXChange.RouteSections.RouteSection.RouteLink.From createTransXChangeRouteSectionsRouteSectionRouteLinkFrom() {
        return new TransXChange.RouteSections.RouteSection.RouteLink.From();
    }

    /**
     * Create an instance of {@link TransXChange.RouteSections.RouteSection.RouteLink.To }
     * 
     */
    public TransXChange.RouteSections.RouteSection.RouteLink.To createTransXChangeRouteSectionsRouteSectionRouteLinkTo() {
        return new TransXChange.RouteSections.RouteSection.RouteLink.To();
    }

    /**
     * Create an instance of {@link TransXChange.StopPoints.StopPoint.Descriptor }
     * 
     */
    public TransXChange.StopPoints.StopPoint.Descriptor createTransXChangeStopPointsStopPointDescriptor() {
        return new TransXChange.StopPoints.StopPoint.Descriptor();
    }

    /**
     * Create an instance of {@link TransXChange.StopPoints.StopPoint.StopClassification.OffStreet.BusAndCoach.Bay }
     * 
     */
    public TransXChange.StopPoints.StopPoint.StopClassification.OffStreet.BusAndCoach.Bay createTransXChangeStopPointsStopPointStopClassificationOffStreetBusAndCoachBay() {
        return new TransXChange.StopPoints.StopPoint.StopClassification.OffStreet.BusAndCoach.Bay();
    }

    /**
     * Create an instance of {@link TransXChange.StopPoints.StopPoint.Place.Location }
     * 
     */
    public TransXChange.StopPoints.StopPoint.Place.Location createTransXChangeStopPointsStopPointPlaceLocation() {
        return new TransXChange.StopPoints.StopPoint.Place.Location();
    }

    /**
     * Create an instance of {@link TransXChange.NptgLocalities.AnnotatedNptgLocalityRef }
     * 
     */
    public TransXChange.NptgLocalities.AnnotatedNptgLocalityRef createTransXChangeNptgLocalitiesAnnotatedNptgLocalityRef() {
        return new TransXChange.NptgLocalities.AnnotatedNptgLocalityRef();
    }

}
