//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.18 at 02:17:15 PM GMT 
//

package org.apache.storm.starter.timetable.xml;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "nptgLocalities", "stopPoints", "routeSections", "routes", "journeyPatternSections",
        "operators", "services", "vehicleJourneys" })
@XmlRootElement(name = "TransXChange")
public class TransXChange implements Serializable{

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    @XmlElement(name = "NptgLocalities", required = true)
    protected TransXChange.NptgLocalities nptgLocalities;
    @XmlElement(name = "StopPoints", required = true)
    protected TransXChange.StopPoints stopPoints;
    @XmlElement(name = "RouteSections", required = true)
    protected TransXChange.RouteSections routeSections;
    @XmlElement(name = "Routes", required = true)
    protected TransXChange.Routes routes;
    @XmlElement(name = "JourneyPatternSections", required = true)
    protected TransXChange.JourneyPatternSections journeyPatternSections;
    @XmlElement(name = "Operators", required = true)
    protected TransXChange.Operators operators;
    @XmlElement(name = "Services", required = true)
    protected TransXChange.Services services;
    @XmlElement(name = "VehicleJourneys", required = true)
    protected TransXChange.VehicleJourneys vehicleJourneys;
    @XmlAttribute(name = "CreationDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDateTime;
    @XmlAttribute(name = "ModificationDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar modificationDateTime;
    @XmlAttribute(name = "Modification")
    protected String modification;
    @XmlAttribute(name = "FileName")
    protected String fileName;
    @XmlAttribute(name = "RevisionNumber")
    protected Byte revisionNumber;
    @XmlAttribute(name = "SchemaVersion")
    protected Float schemaVersion;

    public TransXChange.NptgLocalities getNptgLocalities() {
        return nptgLocalities;
    }

    public void setNptgLocalities(TransXChange.NptgLocalities value) {
        this.nptgLocalities = value;
    }

    public TransXChange.StopPoints getStopPoints() {
        return stopPoints;
    }

    public void setStopPoints(TransXChange.StopPoints value) {
        this.stopPoints = value;
    }

    public TransXChange.RouteSections getRouteSections() {
        return routeSections;
    }

    public void setRouteSections(TransXChange.RouteSections value) {
        this.routeSections = value;
    }

    public TransXChange.Routes getRoutes() {
        return routes;
    }

    public void setRoutes(TransXChange.Routes value) {
        this.routes = value;
    }

    public TransXChange.JourneyPatternSections getJourneyPatternSections() {
        return journeyPatternSections;
    }

    public void setJourneyPatternSections(TransXChange.JourneyPatternSections value) {
        this.journeyPatternSections = value;
    }

    public TransXChange.Operators getOperators() {
        return operators;
    }

    public void setOperators(TransXChange.Operators value) {
        this.operators = value;
    }

    public TransXChange.Services getServices() {
        return services;
    }

    public void setServices(TransXChange.Services value) {
        this.services = value;
    }

    public TransXChange.VehicleJourneys getVehicleJourneys() {
        return vehicleJourneys;
    }

    public void setVehicleJourneys(TransXChange.VehicleJourneys value) {
        this.vehicleJourneys = value;
    }

    public XMLGregorianCalendar getCreationDateTime() {
        return creationDateTime;
    }

    public void setCreationDateTime(XMLGregorianCalendar value) {
        this.creationDateTime = value;
    }

    public XMLGregorianCalendar getModificationDateTime() {
        return modificationDateTime;
    }

    public void setModificationDateTime(XMLGregorianCalendar value) {
        this.modificationDateTime = value;
    }

    public String getModification() {
        return modification;
    }

    public void setModification(String value) {
        this.modification = value;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String value) {
        this.fileName = value;
    }

    public Byte getRevisionNumber() {
        return revisionNumber;
    }

    public void setRevisionNumber(Byte value) {
        this.revisionNumber = value;
    }

    public Float getSchemaVersion() {
        return schemaVersion;
    }

    public void setSchemaVersion(Float value) {
        this.schemaVersion = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "journeyPatternSection" })
    public static class JourneyPatternSections implements Serializable{

        /**
         * 
         */
        private static final long serialVersionUID = 1L;
        @XmlElement(name = "JourneyPatternSection")
        protected List<TransXChange.JourneyPatternSections.JourneyPatternSection> journeyPatternSection;

        public List<TransXChange.JourneyPatternSections.JourneyPatternSection> getJourneyPatternSection() {
            if (journeyPatternSection == null) {
                journeyPatternSection = new ArrayList<TransXChange.JourneyPatternSections.JourneyPatternSection>();
            }
            return this.journeyPatternSection;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "journeyPatternTimingLink" })
        public static class JourneyPatternSection implements Serializable{

            /**
             * 
             */
            private static final long serialVersionUID = 1L;
            @XmlElement(name = "JourneyPatternTimingLink")
            protected List<TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink> journeyPatternTimingLink;
            @XmlAttribute(name = "id")
            protected String id;

            public List<TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink> getJourneyPatternTimingLink() {
                if (journeyPatternTimingLink == null) {
                    journeyPatternTimingLink = new ArrayList<TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink>();
                }
                return this.journeyPatternTimingLink;
            }

            public String getId() {
                return id;
            }

            public void setId(String value) {
                this.id = value;
            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "from", "to", "routeLinkRef", "runTime" })
            public static class JourneyPatternTimingLink implements Serializable{

                /**
                 * 
                 */
                private static final long serialVersionUID = 1L;
                @XmlElement(name = "From", required = true)
                protected TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink.From from;
                @XmlElement(name = "To", required = true)
                protected TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink.To to;
                @XmlElement(name = "RouteLinkRef", required = true)
                protected String routeLinkRef;
                @XmlElement(name = "RunTime", required = true)
                protected Duration runTime;
                @XmlAttribute(name = "id")
                protected String id;

                public TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink.From getFrom() {
                    return from;
                }

                public void setFrom(
                        TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink.From value) {
                    this.from = value;
                }

                public TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink.To getTo() {
                    return to;
                }

                public void setTo(
                        TransXChange.JourneyPatternSections.JourneyPatternSection.JourneyPatternTimingLink.To value) {
                    this.to = value;
                }

                public String getRouteLinkRef() {
                    return routeLinkRef;
                }

                public void setRouteLinkRef(String value) {
                    this.routeLinkRef = value;
                }

                public Duration getRunTime() {
                    return runTime;
                }

                public void setRunTime(Duration value) {
                    this.runTime = value;
                }

                public String getId() {
                    return id;
                }

                public void setId(String value) {
                    this.id = value;
                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "activity", "stopPointRef", "timingStatus" })
                public static class From implements Serializable{

                    /**
                     * 
                     */
                    private static final long serialVersionUID = 1L;
                    @XmlElement(name = "Activity", required = true)
                    protected String activity;
                    @XmlElement(name = "StopPointRef", required = true)
                    protected String stopPointRef;
                    @XmlElement(name = "TimingStatus", required = true)
                    protected String timingStatus;
                    @XmlAttribute(name = "SequenceNumber")
                    protected Byte sequenceNumber;

                    public String getActivity() {
                        return activity;
                    }

                    public void setActivity(String value) {
                        this.activity = value;
                    }

                    public String getStopPointRef() {
                        return stopPointRef;
                    }

                    public void setStopPointRef(String value) {
                        this.stopPointRef = value;
                    }

                    public String getTimingStatus() {
                        return timingStatus;
                    }

                    public void setTimingStatus(String value) {
                        this.timingStatus = value;
                    }

                    public Byte getSequenceNumber() {
                        return sequenceNumber;
                    }

                    public void setSequenceNumber(Byte value) {
                        this.sequenceNumber = value;
                    }

                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "activity", "stopPointRef", "timingStatus" })
                public static class To implements Serializable{

                    /**
                     * 
                     */
                    private static final long serialVersionUID = 1L;
                    @XmlElement(name = "Activity", required = true)
                    protected String activity;
                    @XmlElement(name = "StopPointRef", required = true)
                    protected String stopPointRef;
                    @XmlElement(name = "TimingStatus", required = true)
                    protected String timingStatus;
                    @XmlAttribute(name = "SequenceNumber")
                    protected Byte sequenceNumber;

                    public String getActivity() {
                        return activity;
                    }

                    public void setActivity(String value) {
                        this.activity = value;
                    }

                    public String getStopPointRef() {
                        return stopPointRef;
                    }

                    public void setStopPointRef(String value) {
                        this.stopPointRef = value;
                    }

                    public String getTimingStatus() {
                        return timingStatus;
                    }

                    public void setTimingStatus(String value) {
                        this.timingStatus = value;
                    }

                    public Byte getSequenceNumber() {
                        return sequenceNumber;
                    }

                    public void setSequenceNumber(Byte value) {
                        this.sequenceNumber = value;
                    }

                }

            }

        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "annotatedNptgLocalityRef" })
    public static class NptgLocalities implements Serializable{

        /**
         * 
         */
        private static final long serialVersionUID = 1L;
        @XmlElement(name = "AnnotatedNptgLocalityRef")
        protected List<TransXChange.NptgLocalities.AnnotatedNptgLocalityRef> annotatedNptgLocalityRef;

        public List<TransXChange.NptgLocalities.AnnotatedNptgLocalityRef> getAnnotatedNptgLocalityRef() {
            if (annotatedNptgLocalityRef == null) {
                annotatedNptgLocalityRef = new ArrayList<TransXChange.NptgLocalities.AnnotatedNptgLocalityRef>();
            }
            return this.annotatedNptgLocalityRef;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "nptgLocalityRef", "localityName" })
        public static class AnnotatedNptgLocalityRef implements Serializable{

            /**
             * 
             */
            private static final long serialVersionUID = 1L;
            @XmlElement(name = "NptgLocalityRef", required = true)
            protected String nptgLocalityRef;
            @XmlElement(name = "LocalityName", required = true)
            protected String localityName;

            public String getNptgLocalityRef() {
                return nptgLocalityRef;
            }

            public void setNptgLocalityRef(String value) {
                this.nptgLocalityRef = value;
            }

            public String getLocalityName() {
                return localityName;
            }

            public void setLocalityName(String value) {
                this.localityName = value;
            }

        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "operator" })
    public static class Operators implements Serializable{

        /**
         * 
         */
        private static final long serialVersionUID = 1L;
        @XmlElement(name = "Operator", required = true)
        protected TransXChange.Operators.Operator operator;

        public TransXChange.Operators.Operator getOperator() {
            return operator;
        }

        public void setOperator(TransXChange.Operators.Operator value) {
            this.operator = value;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "operatorCode", "operatorShortName", "operatorNameOnLicence", "tradingName" })
        public static class Operator implements Serializable{

            /**
             * 
             */
            private static final long serialVersionUID = 1L;
            @XmlElement(name = "OperatorCode", required = true)
            protected String operatorCode;
            @XmlElement(name = "OperatorShortName", required = true)
            protected String operatorShortName;
            @XmlElement(name = "OperatorNameOnLicence", required = true)
            protected String operatorNameOnLicence;
            @XmlElement(name = "TradingName", required = true)
            protected String tradingName;
            @XmlAttribute(name = "id")
            protected String id;

            public String getOperatorCode() {
                return operatorCode;
            }

            public void setOperatorCode(String value) {
                this.operatorCode = value;
            }

            public String getOperatorShortName() {
                return operatorShortName;
            }

            public void setOperatorShortName(String value) {
                this.operatorShortName = value;
            }

            public String getOperatorNameOnLicence() {
                return operatorNameOnLicence;
            }

            public void setOperatorNameOnLicence(String value) {
                this.operatorNameOnLicence = value;
            }

            public String getTradingName() {
                return tradingName;
            }

            public void setTradingName(String value) {
                this.tradingName = value;
            }

            public String getId() {
                return id;
            }

            public void setId(String value) {
                this.id = value;
            }

        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "route" })
    public static class Routes implements Serializable{

        /**
         * 
         */
        private static final long serialVersionUID = 1L;
        @XmlElement(name = "Route")
        protected List<TransXChange.Routes.Route> route;

        public List<TransXChange.Routes.Route> getRoute() {
            if (route == null) {
                route = new ArrayList<TransXChange.Routes.Route>();
            }
            return this.route;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "privateCode", "description", "routeSectionRef" })
        public static class Route implements Serializable{

            /**
             * 
             */
            private static final long serialVersionUID = 1L;
            @XmlElement(name = "PrivateCode", required = true)
            protected String privateCode;
            @XmlElement(name = "Description", required = true)
            protected String description;
            @XmlElement(name = "RouteSectionRef", required = true)
            protected String routeSectionRef;
            @XmlAttribute(name = "id")
            protected String id;

            public String getPrivateCode() {
                return privateCode;
            }

            public void setPrivateCode(String value) {
                this.privateCode = value;
            }

            public String getDescription() {
                return description;
            }

            public void setDescription(String value) {
                this.description = value;
            }

            public String getRouteSectionRef() {
                return routeSectionRef;
            }

            public void setRouteSectionRef(String value) {
                this.routeSectionRef = value;
            }

            public String getId() {
                return id;
            }

            public void setId(String value) {
                this.id = value;
            }

        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "routeSection" })
    public static class RouteSections implements Serializable{

        /**
         * 
         */
        private static final long serialVersionUID = 1L;
        @XmlElement(name = "RouteSection")
        protected List<TransXChange.RouteSections.RouteSection> routeSection;

        public List<TransXChange.RouteSections.RouteSection> getRouteSection() {
            if (routeSection == null) {
                routeSection = new ArrayList<TransXChange.RouteSections.RouteSection>();
            }
            return this.routeSection;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "routeLink" })
        public static class RouteSection implements Serializable{

            /**
             * 
             */
            private static final long serialVersionUID = 1L;
            @XmlElement(name = "RouteLink")
            protected List<TransXChange.RouteSections.RouteSection.RouteLink> routeLink;
            @XmlAttribute(name = "id")
            protected String id;

            public List<TransXChange.RouteSections.RouteSection.RouteLink> getRouteLink() {
                if (routeLink == null) {
                    routeLink = new ArrayList<TransXChange.RouteSections.RouteSection.RouteLink>();
                }
                return this.routeLink;
            }

            public String getId() {
                return id;
            }

            public void setId(String value) {
                this.id = value;
            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "from", "to", "distance", "direction" })
            public static class RouteLink implements Serializable{

                /**
                 * 
                 */
                private static final long serialVersionUID = 1L;
                @XmlElement(name = "From", required = true)
                protected TransXChange.RouteSections.RouteSection.RouteLink.From from;
                @XmlElement(name = "To", required = true)
                protected TransXChange.RouteSections.RouteSection.RouteLink.To to;
                @XmlElement(name = "Distance")
                protected short distance;
                @XmlElement(name = "Direction", required = true)
                protected String direction;
                @XmlAttribute(name = "id")
                protected String id;

                public TransXChange.RouteSections.RouteSection.RouteLink.From getFrom() {
                    return from;
                }

                public void setFrom(TransXChange.RouteSections.RouteSection.RouteLink.From value) {
                    this.from = value;
                }

                public TransXChange.RouteSections.RouteSection.RouteLink.To getTo() {
                    return to;
                }

                public void setTo(TransXChange.RouteSections.RouteSection.RouteLink.To value) {
                    this.to = value;
                }

                public short getDistance() {
                    return distance;
                }

                public void setDistance(short value) {
                    this.distance = value;
                }

                public String getDirection() {
                    return direction;
                }

                public void setDirection(String value) {
                    this.direction = value;
                }

                public String getId() {
                    return id;
                }

                public void setId(String value) {
                    this.id = value;
                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "stopPointRef" })
                public static class From implements Serializable{

                    /**
                     * 
                     */
                    private static final long serialVersionUID = 1L;
                    @XmlElement(name = "StopPointRef", required = true)
                    protected String stopPointRef;

                    public String getStopPointRef() {
                        return stopPointRef;
                    }

                    public void setStopPointRef(String value) {
                        this.stopPointRef = value;
                    }

                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "stopPointRef" })
                public static class To implements Serializable{

                    /**
                     * 
                     */
                    private static final long serialVersionUID = 1L;
                    @XmlElement(name = "StopPointRef", required = true)
                    protected String stopPointRef;

                    public String getStopPointRef() {
                        return stopPointRef;
                    }

                    public void setStopPointRef(String value) {
                        this.stopPointRef = value;
                    }

                }

            }

        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "service" })
    public static class Services implements Serializable{

        /**
         * 
         */
        private static final long serialVersionUID = 1L;
        @XmlElement(name = "Service", required = true)
        protected TransXChange.Services.Service service;

        public TransXChange.Services.Service getService() {
            return service;
        }

        public void setService(TransXChange.Services.Service value) {
            this.service = value;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "serviceCode", "privateCode", "lines", "operatingPeriod", "operatingProfile",
                "registeredOperatorRef", "stopRequirements", "mode", "description", "standardService" })
        public static class Service implements Serializable{

            /**
             * 
             */
            private static final long serialVersionUID = 1L;
            @XmlElement(name = "ServiceCode", required = true)
            protected String serviceCode;
            @XmlElement(name = "PrivateCode", required = true)
            protected String privateCode;
            @XmlElement(name = "Lines", required = true)
            protected TransXChange.Services.Service.Lines lines;
            @XmlElement(name = "OperatingPeriod", required = true)
            protected TransXChange.Services.Service.OperatingPeriod operatingPeriod;
            @XmlElement(name = "OperatingProfile", required = true)
            protected TransXChange.Services.Service.OperatingProfile operatingProfile;
            @XmlElement(name = "RegisteredOperatorRef", required = true)
            protected String registeredOperatorRef;
            @XmlElement(name = "StopRequirements", required = true)
            protected TransXChange.Services.Service.StopRequirements stopRequirements;
            @XmlElement(name = "Mode", required = true)
            protected String mode;
            @XmlElement(name = "Description", required = true)
            protected String description;
            @XmlElement(name = "StandardService", required = true)
            protected TransXChange.Services.Service.StandardService standardService;

            public String getServiceCode() {
                return serviceCode;
            }

            public void setServiceCode(String value) {
                this.serviceCode = value;
            }

            public String getPrivateCode() {
                return privateCode;
            }

            public void setPrivateCode(String value) {
                this.privateCode = value;
            }

            public TransXChange.Services.Service.Lines getLines() {
                return lines;
            }

            public void setLines(TransXChange.Services.Service.Lines value) {
                this.lines = value;
            }

            public TransXChange.Services.Service.OperatingPeriod getOperatingPeriod() {
                return operatingPeriod;
            }

            public void setOperatingPeriod(TransXChange.Services.Service.OperatingPeriod value) {
                this.operatingPeriod = value;
            }

            public TransXChange.Services.Service.OperatingProfile getOperatingProfile() {
                return operatingProfile;
            }

            public void setOperatingProfile(TransXChange.Services.Service.OperatingProfile value) {
                this.operatingProfile = value;
            }

            public String getRegisteredOperatorRef() {
                return registeredOperatorRef;
            }

            public void setRegisteredOperatorRef(String value) {
                this.registeredOperatorRef = value;
            }

            public TransXChange.Services.Service.StopRequirements getStopRequirements() {
                return stopRequirements;
            }

            public void setStopRequirements(TransXChange.Services.Service.StopRequirements value) {
                this.stopRequirements = value;
            }

            public String getMode() {
                return mode;
            }

            public void setMode(String value) {
                this.mode = value;
            }

            public String getDescription() {
                return description;
            }

            public void setDescription(String value) {
                this.description = value;
            }

            public TransXChange.Services.Service.StandardService getStandardService() {
                return standardService;
            }

            public void setStandardService(TransXChange.Services.Service.StandardService value) {
                this.standardService = value;
            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "line" })
            public static class Lines implements Serializable{

                /**
                 * 
                 */
                private static final long serialVersionUID = 1L;
                @XmlElement(name = "Line", required = true)
                protected TransXChange.Services.Service.Lines.Line line;

                public TransXChange.Services.Service.Lines.Line getLine() {
                    return line;
                }

                public void setLine(TransXChange.Services.Service.Lines.Line value) {
                    this.line = value;
                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "lineName" })
                public static class Line implements Serializable{

                    /**
                     * 
                     */
                    private static final long serialVersionUID = 1L;
                    @XmlElement(name = "LineName", required = true)
                    protected String lineName;
                    @XmlAttribute(name = "id")
                    protected String id;

                    public String getLineName() {
                        return lineName;
                    }

                    public void setLineName(String value) {
                        this.lineName = value;
                    }

                    public String getId() {
                        return id;
                    }

                    public void setId(String value) {
                        this.id = value;
                    }

                }

            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "startDate", "endDate" })
            public static class OperatingPeriod implements Serializable{

                /**
                 * 
                 */
                private static final long serialVersionUID = 1L;
                @XmlElement(name = "StartDate", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar startDate;
                @XmlElement(name = "EndDate", required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar endDate;

                public XMLGregorianCalendar getStartDate() {
                    return startDate;
                }

                public void setStartDate(XMLGregorianCalendar value) {
                    this.startDate = value;
                }

                public XMLGregorianCalendar getEndDate() {
                    return endDate;
                }

                public void setEndDate(XMLGregorianCalendar value) {
                    this.endDate = value;
                }

            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "regularDayType", "specialDaysOperation", "bankHolidayOperation" })
            public static class OperatingProfile implements Serializable{

                /**
                 * 
                 */
                private static final long serialVersionUID = 1L;
                @XmlElement(name = "RegularDayType", required = true)
                protected TransXChange.Services.Service.OperatingProfile.RegularDayType regularDayType;
                @XmlElement(name = "SpecialDaysOperation", required = true)
                protected TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation specialDaysOperation;
                @XmlElement(name = "BankHolidayOperation", required = true)
                protected TransXChange.Services.Service.OperatingProfile.BankHolidayOperation bankHolidayOperation;

                public TransXChange.Services.Service.OperatingProfile.RegularDayType getRegularDayType() {
                    return regularDayType;
                }

                public void setRegularDayType(TransXChange.Services.Service.OperatingProfile.RegularDayType value) {
                    this.regularDayType = value;
                }

                public TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation getSpecialDaysOperation() {
                    return specialDaysOperation;
                }

                public void setSpecialDaysOperation(
                        TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation value) {
                    this.specialDaysOperation = value;
                }

                public TransXChange.Services.Service.OperatingProfile.BankHolidayOperation getBankHolidayOperation() {
                    return bankHolidayOperation;
                }

                public void setBankHolidayOperation(
                        TransXChange.Services.Service.OperatingProfile.BankHolidayOperation value) {
                    this.bankHolidayOperation = value;
                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "daysOfOperation", "daysOfNonOperation" })
                public static class BankHolidayOperation implements Serializable{

                    /**
                     * 
                     */
                    private static final long serialVersionUID = 1L;
                    @XmlElement(name = "DaysOfOperation", required = true)
                    protected TransXChange.Services.Service.OperatingProfile.BankHolidayOperation.DaysOfOperation daysOfOperation;
                    @XmlElement(name = "DaysOfNonOperation", required = true)
                    protected String daysOfNonOperation;

                    public TransXChange.Services.Service.OperatingProfile.BankHolidayOperation.DaysOfOperation getDaysOfOperation() {
                        return daysOfOperation;
                    }

                    public void setDaysOfOperation(
                            TransXChange.Services.Service.OperatingProfile.BankHolidayOperation.DaysOfOperation value) {
                        this.daysOfOperation = value;
                    }

                    public String getDaysOfNonOperation() {
                        return daysOfNonOperation;
                    }

                    public void setDaysOfNonOperation(String value) {
                        this.daysOfNonOperation = value;
                    }

                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = { "allBankHolidays" })
                    public static class DaysOfOperation implements Serializable{

                        /**
                         * 
                         */
                        private static final long serialVersionUID = 1L;
                        @XmlElement(name = "AllBankHolidays", required = true)
                        protected String allBankHolidays;

                        public String getAllBankHolidays() {
                            return allBankHolidays;
                        }

                        public void setAllBankHolidays(String value) {
                            this.allBankHolidays = value;
                        }

                    }

                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "daysOfWeek" })
                public static class RegularDayType implements Serializable{

                    /**
                     * 
                     */
                    private static final long serialVersionUID = 1L;
                    @XmlElement(name = "DaysOfWeek", required = true)
                    protected TransXChange.Services.Service.OperatingProfile.RegularDayType.DaysOfWeek daysOfWeek;

                    public TransXChange.Services.Service.OperatingProfile.RegularDayType.DaysOfWeek getDaysOfWeek() {
                        return daysOfWeek;
                    }

                    public void setDaysOfWeek(
                            TransXChange.Services.Service.OperatingProfile.RegularDayType.DaysOfWeek value) {
                        this.daysOfWeek = value;
                    }

                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = { "mondayToSunday" })
                    public static class DaysOfWeek implements Serializable{

                        /**
                         * 
                         */
                        private static final long serialVersionUID = 1L;
                        @XmlElement(name = "MondayToSunday", required = true)
                        protected String mondayToSunday;

                        public String getMondayToSunday() {
                            return mondayToSunday;
                        }

                        public void setMondayToSunday(String value) {
                            this.mondayToSunday = value;
                        }

                    }

                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "daysOfNonOperation" })
                public static class SpecialDaysOperation implements Serializable{

                    /**
                     * 
                     */
                    private static final long serialVersionUID = 1L;
                    @XmlElement(name = "DaysOfNonOperation", required = true)
                    protected TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation daysOfNonOperation;

                    public TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation getDaysOfNonOperation() {
                        return daysOfNonOperation;
                    }

                    public void setDaysOfNonOperation(
                            TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation value) {
                        this.daysOfNonOperation = value;
                    }

                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = { "dateRange" })
                    public static class DaysOfNonOperation implements Serializable{

                        /**
                         * 
                         */
                        private static final long serialVersionUID = 1L;
                        @XmlElement(name = "DateRange", required = true)
                        protected TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation.DateRange dateRange;

                        public TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation.DateRange getDateRange() {
                            return dateRange;
                        }

                        public void setDateRange(
                                TransXChange.Services.Service.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation.DateRange value) {
                            this.dateRange = value;
                        }

                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = { "startDate", "endDate" })
                        public static class DateRange implements Serializable{

                            /**
                             * 
                             */
                            private static final long serialVersionUID = 1L;
                            @XmlElement(name = "StartDate", required = true)
                            @XmlSchemaType(name = "date")
                            protected XMLGregorianCalendar startDate;
                            @XmlElement(name = "EndDate", required = true)
                            @XmlSchemaType(name = "date")
                            protected XMLGregorianCalendar endDate;

                            public XMLGregorianCalendar getStartDate() {
                                return startDate;
                            }

                            public void setStartDate(XMLGregorianCalendar value) {
                                this.startDate = value;
                            }

                            public XMLGregorianCalendar getEndDate() {
                                return endDate;
                            }

                            public void setEndDate(XMLGregorianCalendar value) {
                                this.endDate = value;
                            }

                        }

                    }

                }

            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "origin", "destination", "journeyPattern" })
            public static class StandardService implements Serializable{

                /**
                 * 
                 */
                private static final long serialVersionUID = 1L;
                @XmlElement(name = "Origin", required = true)
                protected String origin;
                @XmlElement(name = "Destination", required = true)
                protected String destination;
                @XmlElement(name = "JourneyPattern")
                protected List<TransXChange.Services.Service.StandardService.JourneyPattern> journeyPattern;

                public String getOrigin() {
                    return origin;
                }

                public void setOrigin(String value) {
                    this.origin = value;
                }

                public String getDestination() {
                    return destination;
                }

                public void setDestination(String value) {
                    this.destination = value;
                }

                public List<TransXChange.Services.Service.StandardService.JourneyPattern> getJourneyPattern() {
                    if (journeyPattern == null) {
                        journeyPattern = new ArrayList<TransXChange.Services.Service.StandardService.JourneyPattern>();
                    }
                    return this.journeyPattern;
                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "direction", "operational", "routeRef", "journeyPatternSectionRefs" })
                public static class JourneyPattern implements Serializable{

                    /**
                     * 
                     */
                    private static final long serialVersionUID = 1L;
                    @XmlElement(name = "Direction", required = true)
                    protected String direction;
                    @XmlElement(name = "Operational", required = true)
                    protected TransXChange.Services.Service.StandardService.JourneyPattern.Operational operational;
                    @XmlElement(name = "RouteRef", required = true)
                    protected String routeRef;
                    @XmlElement(name = "JourneyPatternSectionRefs", required = true)
                    protected String journeyPatternSectionRefs;
                    @XmlAttribute(name = "id")
                    protected String id;

                    public String getDirection() {
                        return direction;
                    }

                    public void setDirection(String value) {
                        this.direction = value;
                    }

                    public TransXChange.Services.Service.StandardService.JourneyPattern.Operational getOperational() {
                        return operational;
                    }

                    public void setOperational(
                            TransXChange.Services.Service.StandardService.JourneyPattern.Operational value) {
                        this.operational = value;
                    }

                    public String getRouteRef() {
                        return routeRef;
                    }

                    public void setRouteRef(String value) {
                        this.routeRef = value;
                    }

                    public String getJourneyPatternSectionRefs() {
                        return journeyPatternSectionRefs;
                    }

                    public void setJourneyPatternSectionRefs(String value) {
                        this.journeyPatternSectionRefs = value;
                    }

                    public String getId() {
                        return id;
                    }

                    public void setId(String value) {
                        this.id = value;
                    }

                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = { "vehicleType" })
                    public static class Operational implements Serializable{

                        /**
                         * 
                         */
                        private static final long serialVersionUID = 1L;
                        @XmlElement(name = "VehicleType", required = true)
                        protected TransXChange.Services.Service.StandardService.JourneyPattern.Operational.VehicleType vehicleType;

                        public TransXChange.Services.Service.StandardService.JourneyPattern.Operational.VehicleType getVehicleType() {
                            return vehicleType;
                        }

                        public void setVehicleType(
                                TransXChange.Services.Service.StandardService.JourneyPattern.Operational.VehicleType value) {
                            this.vehicleType = value;
                        }

                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = { "vehicleTypeCode", "description" })
                        public static class VehicleType implements Serializable{

                            /**
                             * 
                             */
                            private static final long serialVersionUID = 1L;
                            @XmlElement(name = "VehicleTypeCode", required = true)
                            protected String vehicleTypeCode;
                            @XmlElement(name = "Description", required = true)
                            protected String description;

                            public String getVehicleTypeCode() {
                                return vehicleTypeCode;
                            }

                            public void setVehicleTypeCode(String value) {
                                this.vehicleTypeCode = value;
                            }

                            public String getDescription() {
                                return description;
                            }

                            public void setDescription(String value) {
                                this.description = value;
                            }

                        }

                    }

                }

            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "noNewStopsRequired" })
            public static class StopRequirements implements Serializable{

                /**
                 * 
                 */
                private static final long serialVersionUID = 1L;
                @XmlElement(name = "NoNewStopsRequired", required = true)
                protected String noNewStopsRequired;

                public String getNoNewStopsRequired() {
                    return noNewStopsRequired;
                }

                public void setNoNewStopsRequired(String value) {
                    this.noNewStopsRequired = value;
                }

            }

        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "stopPoint" })
    public static class StopPoints implements Serializable{

        /**
         * 
         */
        private static final long serialVersionUID = 1L;
        @XmlElement(name = "StopPoint")
        protected List<TransXChange.StopPoints.StopPoint> stopPoint;

        public List<TransXChange.StopPoints.StopPoint> getStopPoint() {
            if (stopPoint == null) {
                stopPoint = new ArrayList<TransXChange.StopPoints.StopPoint>();
            }
            return this.stopPoint;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "atcoCode", "descriptor", "place", "stopClassification",
                "administrativeAreaRef", "notes" })
        public static class StopPoint implements Serializable{

            /**
             * 
             */
            private static final long serialVersionUID = 1L;
            @XmlElement(name = "AtcoCode", required = true)
            protected String atcoCode;
            @XmlElement(name = "Descriptor", required = true)
            protected TransXChange.StopPoints.StopPoint.Descriptor descriptor;
            @XmlElement(name = "Place", required = true)
            protected TransXChange.StopPoints.StopPoint.Place place;
            @XmlElement(name = "StopClassification", required = true)
            protected TransXChange.StopPoints.StopPoint.StopClassification stopClassification;
            @XmlElement(name = "AdministrativeAreaRef")
            protected byte administrativeAreaRef;
            @XmlElement(name = "Notes", required = true)
            protected String notes;
            @XmlAttribute(name = "CreationDateTime")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar creationDateTime;

            public String getAtcoCode() {
                return atcoCode;
            }

            public void setAtcoCode(String value) {
                this.atcoCode = value;
            }

            public TransXChange.StopPoints.StopPoint.Descriptor getDescriptor() {
                return descriptor;
            }

            public void setDescriptor(TransXChange.StopPoints.StopPoint.Descriptor value) {
                this.descriptor = value;
            }

            public TransXChange.StopPoints.StopPoint.Place getPlace() {
                return place;
            }

            public void setPlace(TransXChange.StopPoints.StopPoint.Place value) {
                this.place = value;
            }

            public TransXChange.StopPoints.StopPoint.StopClassification getStopClassification() {
                return stopClassification;
            }

            public void setStopClassification(TransXChange.StopPoints.StopPoint.StopClassification value) {
                this.stopClassification = value;
            }

            public byte getAdministrativeAreaRef() {
                return administrativeAreaRef;
            }

            public void setAdministrativeAreaRef(byte value) {
                this.administrativeAreaRef = value;
            }

            public String getNotes() {
                return notes;
            }

            public void setNotes(String value) {
                this.notes = value;
            }

            public XMLGregorianCalendar getCreationDateTime() {
                return creationDateTime;
            }

            public void setCreationDateTime(XMLGregorianCalendar value) {
                this.creationDateTime = value;
            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "commonName" })
            public static class Descriptor implements Serializable{

                /**
                 * 
                 */
                private static final long serialVersionUID = 1L;
                @XmlElement(name = "CommonName", required = true)
                protected String commonName;

                public String getCommonName() {
                    return commonName;
                }

                public void setCommonName(String value) {
                    this.commonName = value;
                }

            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "nptgLocalityRef", "location" })
            public static class Place implements Serializable{

                /**
                 * 
                 */
                private static final long serialVersionUID = 1L;
                @XmlElement(name = "NptgLocalityRef", required = true)
                protected String nptgLocalityRef;
                @XmlElement(name = "Location", required = true)
                protected TransXChange.StopPoints.StopPoint.Place.Location location;

                public String getNptgLocalityRef() {
                    return nptgLocalityRef;
                }

                public void setNptgLocalityRef(String value) {
                    this.nptgLocalityRef = value;
                }

                public TransXChange.StopPoints.StopPoint.Place.Location getLocation() {
                    return location;
                }

                public void setLocation(TransXChange.StopPoints.StopPoint.Place.Location value) {
                    this.location = value;
                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "easting", "northing" })
                public static class Location implements Serializable{

                    /**
                     * 
                     */
                    private static final long serialVersionUID = 1L;
                    @XmlElement(name = "Easting")
                    protected int easting;
                    @XmlElement(name = "Northing")
                    protected int northing;
                    @XmlAttribute(name = "Precision")
                    protected String precision;

                    public int getEasting() {
                        return easting;
                    }

                    public void setEasting(int value) {
                        this.easting = value;
                    }

                    public int getNorthing() {
                        return northing;
                    }

                    public void setNorthing(int value) {
                        this.northing = value;
                    }

                    public String getPrecision() {
                        return precision;
                    }

                    public void setPrecision(String value) {
                        this.precision = value;
                    }

                }

            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "stopType", "offStreet" })
            public static class StopClassification implements Serializable{

                /**
                 * 
                 */
                private static final long serialVersionUID = 1L;
                @XmlElement(name = "StopType", required = true)
                protected String stopType;
                @XmlElement(name = "OffStreet", required = true)
                protected TransXChange.StopPoints.StopPoint.StopClassification.OffStreet offStreet;

                public String getStopType() {
                    return stopType;
                }

                public void setStopType(String value) {
                    this.stopType = value;
                }

                public TransXChange.StopPoints.StopPoint.StopClassification.OffStreet getOffStreet() {
                    return offStreet;
                }

                public void setOffStreet(TransXChange.StopPoints.StopPoint.StopClassification.OffStreet value) {
                    this.offStreet = value;
                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "busAndCoach" })
                public static class OffStreet implements Serializable{

                    /**
                     * 
                     */
                    private static final long serialVersionUID = 1L;
                    @XmlElement(name = "BusAndCoach", required = true)
                    protected TransXChange.StopPoints.StopPoint.StopClassification.OffStreet.BusAndCoach busAndCoach;

                    public TransXChange.StopPoints.StopPoint.StopClassification.OffStreet.BusAndCoach getBusAndCoach() {
                        return busAndCoach;
                    }

                    public void setBusAndCoach(
                            TransXChange.StopPoints.StopPoint.StopClassification.OffStreet.BusAndCoach value) {
                        this.busAndCoach = value;
                    }

                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = { "bay" })
                    public static class BusAndCoach implements Serializable{

                        @XmlElement(name = "Bay", required = true)
                        protected TransXChange.StopPoints.StopPoint.StopClassification.OffStreet.BusAndCoach.Bay bay;

                        public TransXChange.StopPoints.StopPoint.StopClassification.OffStreet.BusAndCoach.Bay getBay() {
                            return bay;
                        }

                        public void setBay(
                                TransXChange.StopPoints.StopPoint.StopClassification.OffStreet.BusAndCoach.Bay value) {
                            this.bay = value;
                        }

                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = { "timingStatus" })
                        public static class Bay implements Serializable{

                            /**
                             * 
                             */
                            private static final long serialVersionUID = 1L;
                            @XmlElement(name = "TimingStatus", required = true)
                            protected String timingStatus;

                            public String getTimingStatus() {
                                return timingStatus;
                            }

                            public void setTimingStatus(String value) {
                                this.timingStatus = value;
                            }

                        }

                    }

                }

            }

        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "vehicleJourney" })
    public static class VehicleJourneys implements Serializable{

        /**
         * 
         */
        private static final long serialVersionUID = 1L;
        @XmlElement(name = "VehicleJourney")
        protected List<TransXChange.VehicleJourneys.VehicleJourney> vehicleJourney;

        public List<TransXChange.VehicleJourneys.VehicleJourney> getVehicleJourney() {
            if (vehicleJourney == null) {
                vehicleJourney = new ArrayList<TransXChange.VehicleJourneys.VehicleJourney>();
            }
            return this.vehicleJourney;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "privateCode", "destinationDisplay", "operational", "operatingProfile",
                "vehicleJourneyCode", "serviceRef", "lineRef", "journeyPatternRef", "departureTime" })
        public static class VehicleJourney implements Serializable{

            /**
             * 
             */
            private static final long serialVersionUID = 1L;
            @XmlElement(name = "PrivateCode", required = true)
            protected String privateCode;
            @XmlElement(name = "DestinationDisplay", required = true)
            protected String destinationDisplay;
            @XmlElement(name = "Operational", required = true)
            protected TransXChange.VehicleJourneys.VehicleJourney.Operational operational;
            @XmlElement(name = "OperatingProfile", required = true)
            protected TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile operatingProfile;
            @XmlElement(name = "VehicleJourneyCode", required = true)
            protected String vehicleJourneyCode;
            @XmlElement(name = "ServiceRef", required = true)
            protected String serviceRef;
            @XmlElement(name = "LineRef", required = true)
            protected String lineRef;
            @XmlElement(name = "JourneyPatternRef", required = true)
            protected String journeyPatternRef;
            @XmlElement(name = "DepartureTime", required = true)
            @XmlSchemaType(name = "time")
            protected XMLGregorianCalendar departureTime;

            public String getPrivateCode() {
                return privateCode;
            }

            public void setPrivateCode(String value) {
                this.privateCode = value;
            }

            public String getDestinationDisplay() {
                return destinationDisplay;
            }

            public void setDestinationDisplay(String value) {
                this.destinationDisplay = value;
            }

            public TransXChange.VehicleJourneys.VehicleJourney.Operational getOperational() {
                return operational;
            }

            public void setOperational(TransXChange.VehicleJourneys.VehicleJourney.Operational value) {
                this.operational = value;
            }

            public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile getOperatingProfile() {
                return operatingProfile;
            }

            public void setOperatingProfile(TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile value) {
                this.operatingProfile = value;
            }

            public String getVehicleJourneyCode() {
                return vehicleJourneyCode;
            }

            public void setVehicleJourneyCode(String value) {
                this.vehicleJourneyCode = value;
            }

            public String getServiceRef() {
                return serviceRef;
            }

            public void setServiceRef(String value) {
                this.serviceRef = value;
            }

            public String getLineRef() {
                return lineRef;
            }

            public void setLineRef(String value) {
                this.lineRef = value;
            }

            public String getJourneyPatternRef() {
                return journeyPatternRef;
            }

            public void setJourneyPatternRef(String value) {
                this.journeyPatternRef = value;
            }

            public XMLGregorianCalendar getDepartureTime() {
                return departureTime;
            }

            public void setDepartureTime(XMLGregorianCalendar value) {
                this.departureTime = value;
            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "regularDayType", "specialDaysOperation", "bankHolidayOperation" })
            public static class OperatingProfile implements Serializable{

                /**
                 * 
                 */
                private static final long serialVersionUID = 1L;
                @XmlElement(name = "RegularDayType", required = true)
                protected TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.RegularDayType regularDayType;
                @XmlElement(name = "SpecialDaysOperation", required = true)
                protected TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation specialDaysOperation;
                @XmlElement(name = "BankHolidayOperation", required = true)
                protected TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation bankHolidayOperation;

                public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.RegularDayType getRegularDayType() {
                    return regularDayType;
                }

                public void setRegularDayType(
                        TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.RegularDayType value) {
                    this.regularDayType = value;
                }

                public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation getSpecialDaysOperation() {
                    return specialDaysOperation;
                }

                public void setSpecialDaysOperation(
                        TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation value) {
                    this.specialDaysOperation = value;
                }

                public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation getBankHolidayOperation() {
                    return bankHolidayOperation;
                }

                public void setBankHolidayOperation(
                        TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation value) {
                    this.bankHolidayOperation = value;
                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "daysOfOperation", "daysOfNonOperation" })
                public static class BankHolidayOperation implements Serializable{

                    /**
                     * 
                     */
                    private static final long serialVersionUID = 1L;
                    @XmlElement(name = "DaysOfOperation")
                    protected TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation.DaysOfOperation daysOfOperation;
                    @XmlElement(name = "DaysOfNonOperation", required = true)
                    protected TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation.DaysOfNonOperation daysOfNonOperation;

                    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation.DaysOfOperation getDaysOfOperation() {
                        return daysOfOperation;
                    }

                    public void setDaysOfOperation(
                            TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation.DaysOfOperation value) {
                        this.daysOfOperation = value;
                    }

                    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation.DaysOfNonOperation getDaysOfNonOperation() {
                        return daysOfNonOperation;
                    }

                    public void setDaysOfNonOperation(
                            TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.BankHolidayOperation.DaysOfNonOperation value) {
                        this.daysOfNonOperation = value;
                    }

                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = { "christmasDay", "boxingDay", "goodFriday", "newYearsDay",
                            "lateSummerBankHolidayNotScotland", "mayDay", "springBank" })
                    public static class DaysOfNonOperation implements Serializable{

                        /**
                         * 
                         */
                        private static final long serialVersionUID = 1L;
                        @XmlElement(name = "ChristmasDay", required = true)
                        protected String christmasDay;
                        @XmlElement(name = "BoxingDay", required = true)
                        protected String boxingDay;
                        @XmlElement(name = "GoodFriday")
                        protected String goodFriday;
                        @XmlElement(name = "NewYearsDay")
                        protected String newYearsDay;
                        @XmlElement(name = "LateSummerBankHolidayNotScotland")
                        protected String lateSummerBankHolidayNotScotland;
                        @XmlElement(name = "MayDay")
                        protected String mayDay;
                        @XmlElement(name = "SpringBank")
                        protected String springBank;

                        public String getChristmasDay() {
                            return christmasDay;
                        }

                        public void setChristmasDay(String value) {
                            this.christmasDay = value;
                        }

                        public String getBoxingDay() {
                            return boxingDay;
                        }

                        public void setBoxingDay(String value) {
                            this.boxingDay = value;
                        }

                        public String getGoodFriday() {
                            return goodFriday;
                        }

                        public void setGoodFriday(String value) {
                            this.goodFriday = value;
                        }

                        public String getNewYearsDay() {
                            return newYearsDay;
                        }

                        public void setNewYearsDay(String value) {
                            this.newYearsDay = value;
                        }

                        public String getLateSummerBankHolidayNotScotland() {
                            return lateSummerBankHolidayNotScotland;
                        }

                        public void setLateSummerBankHolidayNotScotland(String value) {
                            this.lateSummerBankHolidayNotScotland = value;
                        }

                        public String getMayDay() {
                            return mayDay;
                        }

                        public void setMayDay(String value) {
                            this.mayDay = value;
                        }

                        public String getSpringBank() {
                            return springBank;
                        }

                        public void setSpringBank(String value) {
                            this.springBank = value;
                        }

                    }

                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = { "goodFriday", "newYearsDay", "lateSummerBankHolidayNotScotland",
                            "mayDay", "springBank" })
                    public static class DaysOfOperation implements Serializable{

                        /**
                         * 
                         */
                        private static final long serialVersionUID = 1L;
                        @XmlElement(name = "GoodFriday")
                        protected String goodFriday;
                        @XmlElement(name = "NewYearsDay")
                        protected String newYearsDay;
                        @XmlElement(name = "LateSummerBankHolidayNotScotland")
                        protected String lateSummerBankHolidayNotScotland;
                        @XmlElement(name = "MayDay")
                        protected String mayDay;
                        @XmlElement(name = "SpringBank")
                        protected String springBank;

                        public String getGoodFriday() {
                            return goodFriday;
                        }

                        public void setGoodFriday(String value) {
                            this.goodFriday = value;
                        }

                        public String getNewYearsDay() {
                            return newYearsDay;
                        }

                        public void setNewYearsDay(String value) {
                            this.newYearsDay = value;
                        }

                        public String getLateSummerBankHolidayNotScotland() {
                            return lateSummerBankHolidayNotScotland;
                        }

                        public void setLateSummerBankHolidayNotScotland(String value) {
                            this.lateSummerBankHolidayNotScotland = value;
                        }

                        public String getMayDay() {
                            return mayDay;
                        }

                        public void setMayDay(String value) {
                            this.mayDay = value;
                        }

                        public String getSpringBank() {
                            return springBank;
                        }

                        public void setSpringBank(String value) {
                            this.springBank = value;
                        }

                    }

                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "daysOfWeek" })
                public static class RegularDayType implements Serializable{

                    /**
                     * 
                     */
                    private static final long serialVersionUID = 1L;
                    @XmlElement(name = "DaysOfWeek", required = true)
                    protected TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.RegularDayType.DaysOfWeek daysOfWeek;

                    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.RegularDayType.DaysOfWeek getDaysOfWeek() {
                        return daysOfWeek;
                    }

                    public void setDaysOfWeek(
                            TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.RegularDayType.DaysOfWeek value) {
                        this.daysOfWeek = value;
                    }

                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = { "saturday", "tuesday", "wednesday", "thursday", "friday",
                            "sunday", "monday" })
                    public static class DaysOfWeek implements Serializable{

                        /**
                         * 
                         */
                        private static final long serialVersionUID = 1L;
                        @XmlElement(name = "Saturday")
                        protected String saturday;
                        @XmlElement(name = "Tuesday")
                        protected String tuesday;
                        @XmlElement(name = "Wednesday")
                        protected String wednesday;
                        @XmlElement(name = "Thursday")
                        protected String thursday;
                        @XmlElement(name = "Friday")
                        protected String friday;
                        @XmlElement(name = "Sunday")
                        protected String sunday;
                        @XmlElement(name = "Monday")
                        protected String monday;

                        public String getSaturday() {
                            return saturday;
                        }

                        public void setSaturday(String value) {
                            this.saturday = value;
                        }

                        public String getTuesday() {
                            return tuesday;
                        }

                        public void setTuesday(String value) {
                            this.tuesday = value;
                        }

                        public String getWednesday() {
                            return wednesday;
                        }

                        public void setWednesday(String value) {
                            this.wednesday = value;
                        }

                        public String getThursday() {
                            return thursday;
                        }

                        public void setThursday(String value) {
                            this.thursday = value;
                        }

                        public String getFriday() {
                            return friday;
                        }

                        public void setFriday(String value) {
                            this.friday = value;
                        }

                        public String getSunday() {
                            return sunday;
                        }

                        public void setSunday(String value) {
                            this.sunday = value;
                        }

                        public String getMonday() {
                            return monday;
                        }

                        public void setMonday(String value) {
                            this.monday = value;
                        }

                    }

                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "daysOfNonOperation", "daysOfOperation" })
                public static class SpecialDaysOperation implements Serializable{

                    /**
                     * 
                     */
                    private static final long serialVersionUID = 1L;
                    @XmlElement(name = "DaysOfNonOperation")
                    protected TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation daysOfNonOperation;
                    @XmlElement(name = "DaysOfOperation")
                    protected TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfOperation daysOfOperation;

                    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation getDaysOfNonOperation() {
                        return daysOfNonOperation;
                    }

                    public void setDaysOfNonOperation(
                            TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation value) {
                        this.daysOfNonOperation = value;
                    }

                    public TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfOperation getDaysOfOperation() {
                        return daysOfOperation;
                    }

                    public void setDaysOfOperation(
                            TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfOperation value) {
                        this.daysOfOperation = value;
                    }

                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = { "dateRange" })
                    public static class DaysOfNonOperation implements Serializable{

                        /**
                         * 
                         */
                        private static final long serialVersionUID = 1L;
                        @XmlElement(name = "DateRange")
                        protected List<TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation.DateRange> dateRange;

                        public List<TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation.DateRange> getDateRange() {
                            if (dateRange == null) {
                                dateRange = new ArrayList<TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfNonOperation.DateRange>();
                            }
                            return this.dateRange;
                        }

                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = { "startDate", "endDate", "note" })
                        public static class DateRange implements Serializable{

                            /**
                             * 
                             */
                            private static final long serialVersionUID = 1L;
                            @XmlElement(name = "StartDate", required = true)
                            @XmlSchemaType(name = "date")
                            protected XMLGregorianCalendar startDate;
                            @XmlElement(name = "EndDate", required = true)
                            @XmlSchemaType(name = "date")
                            protected XMLGregorianCalendar endDate;
                            @XmlElement(name = "Note")
                            protected String note;

                            public XMLGregorianCalendar getStartDate() {
                                return startDate;
                            }

                            public void setStartDate(XMLGregorianCalendar value) {
                                this.startDate = value;
                            }

                            public XMLGregorianCalendar getEndDate() {
                                return endDate;
                            }

                            public void setEndDate(XMLGregorianCalendar value) {
                                this.endDate = value;
                            }

                            public String getNote() {
                                return note;
                            }

                            public void setNote(String value) {
                                this.note = value;
                            }

                        }

                    }

                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = { "dateRange" })
                    public static class DaysOfOperation implements Serializable{

                        /**
                         * 
                         */
                        private static final long serialVersionUID = 1L;
                        @XmlElement(name = "DateRange")
                        protected List<TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfOperation.DateRange> dateRange;

                        public List<TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfOperation.DateRange> getDateRange() {
                            if (dateRange == null) {
                                dateRange = new ArrayList<TransXChange.VehicleJourneys.VehicleJourney.OperatingProfile.SpecialDaysOperation.DaysOfOperation.DateRange>();
                            }
                            return this.dateRange;
                        }

                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = { "startDate", "endDate", "note" })
                        public static class DateRange implements Serializable{

                            /**
                             * 
                             */
                            private static final long serialVersionUID = 1L;
                            @XmlElement(name = "StartDate", required = true)
                            @XmlSchemaType(name = "date")
                            protected XMLGregorianCalendar startDate;
                            @XmlElement(name = "EndDate", required = true)
                            @XmlSchemaType(name = "date")
                            protected XMLGregorianCalendar endDate;
                            @XmlElement(name = "Note")
                            protected String note;

                            public XMLGregorianCalendar getStartDate() {
                                return startDate;
                            }

                            public void setStartDate(XMLGregorianCalendar value) {
                                this.startDate = value;
                            }

                            public XMLGregorianCalendar getEndDate() {
                                return endDate;
                            }

                            public void setEndDate(XMLGregorianCalendar value) {
                                this.endDate = value;
                            }

                            public String getNote() {
                                return note;
                            }

                            public void setNote(String value) {
                                this.note = value;
                            }

                        }

                    }

                }

            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "vehicleType" })
            public static class Operational implements Serializable{

                /**
                 * 
                 */
                private static final long serialVersionUID = 1L;
                @XmlElement(name = "VehicleType", required = true)
                protected TransXChange.VehicleJourneys.VehicleJourney.Operational.VehicleType vehicleType;

                public TransXChange.VehicleJourneys.VehicleJourney.Operational.VehicleType getVehicleType() {
                    return vehicleType;
                }

                public void setVehicleType(TransXChange.VehicleJourneys.VehicleJourney.Operational.VehicleType value) {
                    this.vehicleType = value;
                }

                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = { "vehicleTypeCode", "description" })
                public static class VehicleType implements Serializable{

                    /**
                     * 
                     */
                    private static final long serialVersionUID = 1L;
                    @XmlElement(name = "VehicleTypeCode", required = true)
                    protected String vehicleTypeCode;
                    @XmlElement(name = "Description", required = true)
                    protected String description;

                    public String getVehicleTypeCode() {
                        return vehicleTypeCode;
                    }

                    public void setVehicleTypeCode(String value) {
                        this.vehicleTypeCode = value;
                    }

                    public String getDescription() {
                        return description;
                    }

                    public void setDescription(String value) {
                        this.description = value;
                    }

                }

            }

        }

    }

}
